// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: branch_users.sql

package generated

import (
	"context"
)

const deleteBranchUserByUserId = `-- name: DeleteBranchUserByUserId :exec
DELETE FROM branch_users WHERE user_id = $1
`

func (q *Queries) DeleteBranchUserByUserId(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, deleteBranchUserByUserId, userID)
	return err
}
