// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: good.sql

package generated

import (
	"context"
)

const addGoodToBrand = `-- name: AddGoodToBrand :exec
INSERT INTO brand_goods (brand_id, good_id)
VALUES ($1, $2)
`

type AddGoodToBrandParams struct {
	BrandID int32 `json:"brand_id"`
	GoodID  int32 `json:"good_id"`
}

func (q *Queries) AddGoodToBrand(ctx context.Context, arg AddGoodToBrandParams) error {
	_, err := q.db.ExecContext(ctx, addGoodToBrand, arg.BrandID, arg.GoodID)
	return err
}

const createGood = `-- name: CreateGood :one
INSERT INTO goods (name, description)
VALUES ($1, $2) RETURNING id
`

type CreateGoodParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateGood(ctx context.Context, arg CreateGoodParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createGood, arg.Name, arg.Description)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const disableGood = `-- name: DisableGood :exec
INSERT INTO disabled_goods (good_id)
VALUES ($1)
`

func (q *Queries) DisableGood(ctx context.Context, goodID int32) error {
	_, err := q.db.ExecContext(ctx, disableGood, goodID)
	return err
}

const getGoodBySaleId = `-- name: GetGoodBySaleId :one
SELECT g.id, g.name, g.description
FROM goods g
         JOIN sales_goods sg ON g.id = sg.good_id
WHERE sg.sale_id = $1
`

type GetGoodBySaleIdRow struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) GetGoodBySaleId(ctx context.Context, saleID int32) (GetGoodBySaleIdRow, error) {
	row := q.db.QueryRowContext(ctx, getGoodBySaleId, saleID)
	var i GetGoodBySaleIdRow
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const getGoodsByBrandId = `-- name: GetGoodsByBrandId :many
SELECT m.id, m.name, m.description
FROM goods m
         JOIN brand_goods bm ON m.id = bm.good_id
WHERE bm.brand_id = $1
  AND NOT EXISTS (
    SELECT 1
    FROM disabled_goods dg
    WHERE dg.good_id = m.id
)
`

type GetGoodsByBrandIdRow struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) GetGoodsByBrandId(ctx context.Context, brandID int32) ([]GetGoodsByBrandIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getGoodsByBrandId, brandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGoodsByBrandIdRow
	for rows.Next() {
		var i GetGoodsByBrandIdRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
