// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package generated

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type ValueType string

const (
	ValueTypeAmount ValueType = "amount"
	ValueTypeCount  ValueType = "count"
)

func (e *ValueType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ValueType(s)
	case string:
		*e = ValueType(s)
	default:
		return fmt.Errorf("unsupported scan type for ValueType: %T", src)
	}
	return nil
}

type NullValueType struct {
	ValueType ValueType
	Valid     bool // Valid is true if ValueType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullValueType) Scan(value interface{}) error {
	if value == nil {
		ns.ValueType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ValueType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullValueType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ValueType), nil
}

type Branch struct {
	ID          int32     `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type BranchBrand struct {
	ID       int32 `json:"id"`
	BranchID int32 `json:"branch_id"`
	BrandID  int32 `json:"brand_id"`
}

type BranchBrandSaleTypeGoal struct {
	ID          int32         `json:"id"`
	BranchBrand sql.NullInt32 `json:"branch_brand"`
	SaleTypeID  sql.NullInt32 `json:"sale_type_id"`
	Value       int64         `json:"value"`
	FromDate    time.Time     `json:"from_date"`
	ToDate      time.Time     `json:"to_date"`
}

type BranchUser struct {
	ID       int32         `json:"id"`
	UserID   sql.NullInt32 `json:"user_id"`
	BranchID sql.NullInt32 `json:"branch_id"`
}

type Brand struct {
	ID          int32     `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type Comment struct {
	ID        int32     `json:"id"`
	Body      string    `json:"body"`
	UserID    int32     `json:"user_id"`
	PostID    int32     `json:"post_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Department struct {
	ID          int32     `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type DisabledUser struct {
	UserID     int32     `json:"user_id"`
	DisabledAt time.Time `json:"disabled_at"`
}

type Like struct {
	UserID int32 `json:"user_id"`
	PostID int32 `json:"post_id"`
}

type Post struct {
	ID        int32     `json:"id"`
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	UserID    int32     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type PostImage struct {
	ID       int32  `json:"id"`
	ImageUrl string `json:"image_url"`
	PostID   int32  `json:"post_id"`
}

type Role struct {
	ID          int32     `json:"id"`
	Title       string    `json:"title"`
	Key         string    `json:"key"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type Sale struct {
	ID          int32     `json:"id"`
	UserID      int32     `json:"user_id"`
	SaleDate    time.Time `json:"sale_date"`
	Amount      int64     `json:"amount"`
	SaleTypeID  int32     `json:"sale_type_id"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type SaleType struct {
	ID          int32     `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	Color       string    `json:"color"`
	Gravity     int32     `json:"gravity"`
	ValueType   ValueType `json:"value_type"`
}

type SalesBrand struct {
	SaleID  int32 `json:"sale_id"`
	BrandID int32 `json:"brand_id"`
}

type User struct {
	ID        int32     `json:"id"`
	Phone     string    `json:"phone"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	CreatedAt time.Time `json:"created_at"`
}

type UserAvatarView struct {
	ID        int32  `json:"id"`
	Phone     string `json:"phone"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	AvatarUrl string `json:"avatar_url"`
}

type UserBrand struct {
	ID      int32 `json:"id"`
	UserID  int32 `json:"user_id"`
	BrandID int32 `json:"brand_id"`
}

type UserBrandSaleTypeGoal struct {
	ID         int32     `json:"id"`
	UserBrand  int32     `json:"user_brand"`
	SaleTypeID int32     `json:"sale_type_id"`
	Value      int64     `json:"value"`
	FromDate   time.Time `json:"from_date"`
	ToDate     time.Time `json:"to_date"`
}

type UserBrandSaleTypeRatio struct {
	UserID     int32     `json:"user_id"`
	BrandID    int32     `json:"brand_id"`
	SaleTypeID int32     `json:"sale_type_id"`
	Ratio      float32   `json:"ratio"`
	FromDate   time.Time `json:"from_date"`
	ToDate     time.Time `json:"to_date"`
}

type UserRole struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
	RoleID int32 `json:"role_id"`
}

type UsersAvatar struct {
	UserID    int32  `json:"user_id"`
	AvatarUrl string `json:"avatar_url"`
}

type UsersCode struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	Code      int32     `json:"code"`
	CreatedAt time.Time `json:"created_at"`
}
