// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: owner.sql

package generated

import (
	"context"
)

const getOwnerByUserId = `-- name: GetOwnerByUserId :one
SELECT user_id, phone, first_name, last_name, avatar_url, owner_id
FROM owners_view o
WHERE o.user_id = $1
`

func (q *Queries) GetOwnerByUserId(ctx context.Context, userID int32) (OwnersView, error) {
	row := q.db.QueryRowContext(ctx, getOwnerByUserId, userID)
	var i OwnersView
	err := row.Scan(
		&i.UserID,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.OwnerID,
	)
	return i, err
}
