name: Dev Workflow

on:
  create:
    branches:
      - 'release-v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restart Application on Server
        uses: appleboy/ssh-action@v1.0.0

        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          username: ${{ secrets.DEV_SSH_USER }}
          password: ${{ secrets.DEV_SSH_PASSWORD }}
          script: cd /root/backend && chmod +x dev.restart.sh && git pull origin ${{ github.ref }} && /usr/libexec/docker/cli-plugins/docker-compose -f docker-compose.dev.yml up --build -d app && /usr/libexec/docker/cli-plugins/docker-compose -f docker-compose.dev.yml restart nginx 
