# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'

    - name: Build
      run: |
        CGO_ENABLED=0 GOOS=linux go build -o main .
      
    - name: Install SSH Pass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Transfer Binary to Server
      env:
        SSH_PASS: daX4vNWD
      run: |
        sshpass -p $SSH_PASS scp -o StrictHostKeyChecking=no main root@185.182.219.90:/root/test

    - name: Restart Application on Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 185.182.219.90
        username: root
        password: daX4vNWD
        # port: ${{ secrets.PORT }}
        script: ls
        
    # - name: Restart Application on Server
    #   env:
    #     SSH_PASS: ${{ secrets.SSH_PASSWORD }}
    #   run: |
    #     sshpass -p $SSH_PASS ssh root@185.182.219.90 'ls'
