name: Prod Workflow

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Build binary
        run: |
          CGO_ENABLED=0 GOOS=linux go build -o main .

      - name: Install SSH Pass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Transfer Binary to Server
        env:
          PASS: ${{ secrets.PROD_SSH_PASSWORD }}
          USER: ${{ secrets.PROD_SSH_USER }}
          HOST: ${{ secrets.PROD_SERVER_IP }}
          PORT: ${{ secrets.PROD_SSH_PORT }}
        run: |
          sshpass -p $PASS scp -P $PORT -o StrictHostKeyChecking=no -r templates/ main $USER@$HOST:/home/admsrv/backend

      - name: Restart Application on Server
        uses: appleboy/ssh-action@v1.0.0

        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          port: ${{ secrets.PROD_SSH_PORT }}
          username: ${{ secrets.PROD_SSH_USER }}
          password: ${{ secrets.PROD_SSH_PASSWORD }}
          script: cd /home/admsrv/backend && ./prod.restart.sh
